# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables"]

pgp_key: BAA0 2E14 BB58 1531 ED84 F3AD 3745 6162 1157 EF38

# Permalinks
permalink: pretty

# Setup
title: Danny
tagline: Singer, open-source dev, native Omahan
url: https://dannydenenberg.com
shorturl: dannydenenberg.com

author:
  name: Danny Denenberg
  url: https://twitter.com/dannydenenberg_

paginate: 1

# Custom vars
version: 1.0.0

github:
  repo: github.com/dannydenenberg/dannydenenberg.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  About: "/about/"
  Archive: "/archive"
  Projects: "/projects"
  Contact: "/contact"

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate

contact_links:
  - name: Twitter
    url: https://twitter.com/dannydenenberg_
    icon: twitter
  - name: Facebook
    url: https://www.facebook.com/daniel.denenberg.18
    icon: facebook-f
  - name: LinkedIn
    url: https://www.linkedin.com/in/dannydenenberg
    icon: linkedin-in
  - name: GitHub
    url: https://github.com/dannydenenberg
    icon: github
  - name: Keybase
    url: https://keybase.io/dannydenenberg
    icon: keybase
