# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables"]

# highlighter: true
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Danny Denenberg
tagline: ""
url: http://www.dannydenenberg.com
shorturl: dannydenenberg.com

author:
  name: "Danny Denenberg"
  url: https://instagram.com/dannydenenberg

paginate: 1

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version: 1.0.0

github:
  repo: github.com/dannydenenberg/dannydenenberg.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  Resume: "/danny's resume.pdf"
  About: "/about/"
  Listings: "/listings/"
  Projects: "/projects/"
  Feed: "/atom.xml"

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
