# Permalinks
permalink:           pretty

# Setup
title:               Danny Denenberg
tagline:             
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# math
markdown: kramdown
kramdown:
   math_engine: mathjax

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Danny Denenberg
  url:               https://twitter.com/dannydenenberg_
  email:             dannydenenberg@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/dannydenenberg/dannydenenberg.github.io

# nav bar 
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
