# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables"]

baseurl: "https://dannydenenberg.com/"

# Permalinks
permalink: pretty

# Setup
title: Danny D.
tagline: Singer, open-source dev, native Omahan
url: https://dannydenenberg.com
shorturl: dannydenenberg.com

# tagline:          'A Jekyll theme'
description: "Hey <a>links</a> work."

author:
  name: Danny Denenberg
  url: https://twitter.com/dannydenenberg_

paginate: 1

# Custom vars
version: "1.lots.of.edits"

github:
  repo: github.com/dannydenenberg/dannydenenberg.github.io

# This is the list of pages to include in the header of the website.
pages_list:
  "About": "/about/"
  "Archive": "/archive"
  "Feed": "/atom.xml"

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate

plugins:
  # - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-compress-images

# where to compress images
compress_images:
  images_path: "/goods/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  svgo: false

exclude:
  - .jekyll-cache
  - _compress_images_cache.yml

contact_links:
  # - name: LinkedIn
  #   url: https://www.linkedin.com/in/dannydenenberg
  #   icon: linkedin-in
  - name: GitHub
    url: https://github.com/dannydenenberg
    icon: github
  - name: Keybase
    url: https://keybase.io/dannydenenberg
    icon: keybase
  - name: Twitter
    url: https://twitter.com/dannydenenberg_
    icon: twitter
####### _config.yml from Hyde GitHub page ######
# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# # Permalinks
# permalink:        pretty
# relative_permalinks: true

# # Setup
# title:            Hyde
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:              http://hyde.getpoole.com
# baseurl:          /

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

# paginate:         5

# # Custom vars
# version:          2.1.0

# github:
#   repo:           https://github.com/poole/hyde
